### PR TITLE
Fixed container-compose script, updated README with dev & update inst…

### PR DESCRIPTION
**Pull request by johnaohara**
…ructions

### CODE REVIEW

**Comment by johnaohara** [comment]
Please can someone review these changes and confirm that local dev mode works for them with `docker-compose` and/or `podman-compose`? If it works, can someone approve these changes? thanks

**Comment by rvansa** [comment]
Some things that don't work OOTB:
* use docker.io/hubci/hugo (to prevent shortname resolution trouble)
* `podman-compose` does not need the `-f` option. Maybe stick to docker-compose.yaml so that you don't need to specify it for `docker-compose`.
* use different port than docs.app-svc-perf ? (otherwise I have conflict when running both at the same time)

However I am getting this error:
```
14:52:25@rvansa redhatperf.github.io$ podman-compose up
['podman', '--version', '']
using podman version: 4.2.1
** excluding:  set()
['podman', 'network', 'exists', 'redhatperfgithubio_default']
podman create --name=redhatperfgithubio_live-preview_1 --label io.podman.compose.config-hash=123 --label io.podman.compose.project=redhatperfgithubio --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=redhatperfgithubio --label com.docker.compose.project.working_dir=/home/rvansa/workspace/redhatperf.github.io --label com.docker.compose.project.config_files=container-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=live-preview -v /home/rvansa/workspace/redhatperf.github.io:/home/circleci/project:rw --net redhatperfgithubio_default --network-alias live-preview -p 1313:1313 -u root --stop-signal SIGTERM hubci/hugo:0.105 /usr/bin/hugo server -D --bind=0.0.0.0 --baseURL=http://0.0.0.0 --port=1313
1ef1a99fd7981b53e8f775420b209669a90e6e28aa0c0e658d0fc01bacff4c39
exit code: 0
podman start -a redhatperfgithubio_live-preview_1
Error: open /home/circleci/project: permission denied
exit code: 255
```
Docker-compose fails with the same issue.

**Comment by rvansa** [comment]
Oh yeah, it's the classical issue with SELinux: missing relabeling `Z` on a `rw` volume. When I add that it works just fine.

**Comment by johnaohara** [comment]
@rvansa thanks for the feedback, have pushed changes based on your comments

**Review by rvansa — APPROVED** [review]

**Comment by johnaohara** [comment]
@rvansa thanks

**Pull request merged**
